const data = {
  categories: [
    {
      name: '超值全餐',
      enname:'extra value meals',
      image: '/images/extra-value-meals.jpg',
    },
    {
      name: '極選系列',
      enname:'signature series',
      image: '/images/signature-series.jpg',
    },
    {
      name: 'Happy Meal',
      enname:'happy meal',
      image: '/images/happy-meal.jpg',
    },
    {
      name: '銅板輕鬆點',
      enname:'50 dollars meal',
      image: '/images/50-dollars-meal.jpg',
    },
    {
      name: '飲料及點心',
      enname:'beverages and snacks',
      image: '/images/beverages.jpg',
    },
    {
      name: '麥當勞分享盒',
      enname:'happy sharing box',
      image: '/images/happy-sharing-box.jpg',
    },

  ],
  categories1: [
    {
      name: '配餐',
      enname:'sideorder',
      image: '/images/sideorder.jpg',
    },
    {
      name: '配餐飲料',
      enname:'sideorder drink',
      image: '/images/sideorderdrink.jpg',
    },
    {
      name: '加價購',
      enname:'extra',
      image: '/images/images.png',
    },
  ],
  products: [
    {
      category: '飲料及點心',
      encategory:'beverages and snacks',
      name: '冰經典那堤',
      enname:'iced latte',
      calorie: 111,
      price: 75,
      image: '/images/beverages-and-snacks/latte-iced.jpg',
    },
    {
      category: '飲料及點心',
      encategory:'beverages and snacks',
      name: '鮮乳',
      enname:'Milk',
      calorie: 160,
      price: 33,
      image: '/images/beverages-and-snacks/Milk.jpg',
    },
    {
      category: '飲料及點心',
      name: '熱奶茶',
      enname:'hot milktea',
      calorie: 265,
      price: 35,
      image: '/images/beverages-and-snacks/milk-tea-hot.jpg',
    },
    {
      category: '飲料及點心',
      name: '冰奶茶',
      enname:'iced milktea',
      calorie: 128,
      price: 38,
      image: '/images/beverages-and-snacks/milk-tea-iced.jpg',
    },
    {
      category: '飲料及點心',
      name: '柳橙汁',
      enname:'orange-juice',
      calorie: 154,
      price: 40,
      image: '/images/beverages-and-snacks/Orange-Juice.jpg',
    },
    {
      category: '飲料及點心',
      name: '雪碧',
      enname:'sprite',
      calorie: 163,
      price: 38,
      image: '/images/beverages-and-snacks/sprite.jpg',
    },
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////麥當勞分享盒
    {
      category: '麥當勞分享盒',
      name: '麥脆鷄腿分享盒(6塊)',
      enname:'chicken mccrispy sharing box 6 pieces',
      calorie: 3298,
      price: 369,
      image: '/images/happy-sharing-box/hsb-mccrispy-6pcs.jpg',
    },
    {
      category: '麥當勞分享盒',
      name: '酥嫩鷄翅分享盒',
      enname:'tender chicken wing sharing box',
      calorie: 1628,
      price: 249,
      image: '/images/happy-sharing-box/hsb-tender-wings.jpg',
    },
    {
      category: '麥當勞分享盒',
      name: '勁辣香鷄翅分享盒',
      enname:'spicy chicken wing sharing box',
      calorie: 2278,
      price: 249,
      image: '/images/happy-sharing-box/hsb-spicy-wings.jpg',
    },
    {
      category: '麥當勞分享盒',
      name: '麥克鷄塊分享盒(20塊)',
      enname:'chicken mcnuggets sharing box 20 pieces',
      calorie: 1428,
      price: 199,
      image: '/images/happy-sharing-box/hsb-mcnuggets.jpg',
    },
    {
      category: '麥當勞分享盒',
      name: '麥克鷄塊分享盒(30塊)',
      enname:'chicken mcnuggets sharing box 30 pieces',
      calorie: 1877,
      price: 289,
      image: '/images/happy-sharing-box/chicken-mcnuggets-sharing-box-6-pieces.jpg',
    },
    {
      category: '麥當勞分享盒',
      name: '鷄塊鷄腿分享盒',
      enname:'chicken & mcnuggets sharing box',
      calorie: 3747,
      price: 479,
      image: '/images/happy-sharing-box/chicken-mcnuggets-n-mccrispy-sharing-box.jpg',
    },

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////超值全餐
    {
      category: '超值全餐',
      name: '大麥克',
      enname:'Big-Mac',
      calorie: 548,
      price: 80,
      image: '/images/extra-value-meals/EVM-01-Big-Mac.jpg',
    },
    {
      category: '超值全餐',
      name: '雙層牛肉吉事堡',
      calorie: 467,
      enname:'double-cheese-burger',
      price: 70,
      image: '/images/extra-value-meals/EVM-02-D-Cheeseburger.jpg',
    },
    {
      category: '超值全餐',
      name: '嫩煎鷄腿堡',
      enname:'grilled-bbq-chicken-burger',
      calorie: 363,
      price: 80,
      image: '/images/extra-value-meals/EVM-04-GBC.jpg',
    },
    {
      category: '超值全餐',
      name: '麥香鷄',
      enname:'mcchicken',
      calorie: 360,
      price: 49,
      image: '/images/extra-value-meals/EVM-05-McChicken.jpg',
    },
    {
      category: '超值全餐',
      name: '麥克鷄塊(6塊)',
      enname:'chicken-mcnuggets-6-pieces',
      calorie: 270,
      price: 64,
      image: '/images/extra-value-meals/EVM-06-NGT6.jpg',
    },
    {
      category: '超值全餐',
      name: '麥克鷄塊(10塊)',
      enname:'chicken-mcnuggets-10-pieces',
      calorie: 449,
      price: 104,
      image: '/images/extra-value-meals/EVM-06-NGT10.jpg',
    },
    {
      category: '超值全餐',
      name: '勁辣鷄腿堡',
      enname:'spicy-chicken-filet-burger',
      calorie: 493,
      price: 80,
      image: '/images/extra-value-meals/EVM-08-SCF.jpg',
    },
    {
      category: '超值全餐',
      name: '原味麥脆鷄翅(2塊)',
      enname:'chicken-mccrispy-wing-2-pieces',
      calorie: 611,
      price: 98,
      image: '/images/extra-value-meals/EVM-10-MFC.jpg',
    },
    {
      category: '超值全餐',
      name: '辣味麥脆鷄翅(2塊)',
      enname:'spicy-chicken-mccrispy-wing-2-pieces',
      calorie: 612,
      price: 98,
      image: '/images/extra-value-meals/EVM-10-MFC-spicy.jpg',
    },
    {
      category: '超值全餐',
      name: '原味麥脆鷄腿(2塊)',
      enname:'chicken-mccrispy-2-pieces',
      calorie: 747,
      price: 120,
      image: '/images/extra-value-meals/EVM-09-MFC.jpg',
    },
    {
      category: '超值全餐',
      name: '辣味麥脆鷄腿(2塊)',
      enname:'spicy-chicken-mccrispy-2-pieces',
      calorie: 765,
      price: 120,
      image: '/images/extra-value-meals/EVM-09-MFC-spicy.jpg',
    },
    {
      category: '超值全餐',
      name: '麥香魚',
      enname:'filet-o-fish',
      calorie: 330,
      price: 60,
      image: '/images/extra-value-meals/EVM-12-FOF.jpg',
    },
    {
      category: '超值全餐',
      name: '薑燒豬肉長堡',
      enname:'ginger-pork-long-burger',
      calorie: 483,
      price: 84,
      image: '/images/extra-value-meals/Ginger-pork-long-burger.jpg',
    },
    {
      category: '超值全餐',
      name: '煙燻鷄肉長堡',
      enname:'smoked-chicken-long-burger',
      calorie: 381,
      price: 84,
      image: '/images/extra-value-meals/Smoked-chicken-long-burger.jpg',
    },
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////極選系列
    
    {
      category: '極選系列',
      name: '蕈菇安格斯黑牛堡',
      enname:'mushroom-angus-beef-burger',
      calorie: 575,
      price: 124,
      image: '/images/extra-value-meals/signature-mushroom-beef.jpg',
    },
    {
      category: '極選系列',
      name: 'BLT 安格斯黑牛堡',
      enname:'blt-angus-beef-burger',
      calorie: 544,
      price: 114,
      image: '/images/extra-value-meals/signature-blt-beef.jpg',
    },
    {
      category: '極選系列',
      name: 'BLT 辣脆鷄腿堡',
      enname:'blt-spicy-chicken-burger',
      calorie: 554,
      price: 114,
      image: '/images/extra-value-meals/signature-blt-fried-chicken.jpg',
    },
    {
      category: '極選系列',
      name: 'BLT 嫩煎鷄腿堡',
      enname:'blt-grilled-chicken-burger',
      calorie: 455,
      price: 114,
      image: '/images/extra-value-meals/signature-blt-grilled-chicken.jpg',
    },
    {
      category: '極選系列',
      name: '凱撒辣脆鷄沙拉',
      enname:'caesar-salad-with-spicy-fried-chicken-filet',
      calorie: 347,
      price: 104,
      image: '/images/extra-value-meals/signature-spicy-fried-chicken-salad.jpg',
    },
    {
      category: '極選系列',
      name: '義式烤鷄沙拉',
      enname:'italian-salad-with-grilled-chicken-filet',
      calorie: 248,
      price: 104,
      image: '/images/extra-value-meals/signature-grilled-chicken-salad.jpg',
    },

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////飲料及點心
    {
      category: '飲料及點心',
      name: '經典美式咖啡',
      enname:'americano',
      calorie: 14,
      price: 65,
      image: '/images/beverages-and-snacks/americano-hot.jpg',
    },
    {
      category: '飲料及點心',
      name: '冰經典美式咖啡',
      enname:'iced-americano',
      calorie: 19,
      price: 65,
      image: '/images/beverages-and-snacks/americano-iced.jpg',
    },
    {
      category: '飲料及點心',
      name: '阿薩姆鮮奶茶',
      enname:'assam milktea',
      calorie: 183,
      price: 75,
      image: '/images/beverages-and-snacks/assam-milk-tea-hot.jpg',
    },
    {
      category: '飲料及點心',
      name: '冰阿薩姆鮮奶茶',
      enname:'iced assam milktea',
      calorie: 183,
      price: 75,
      image: '/images/beverages-and-snacks/assam-milk-tea-iced.jpg',
    },
    {
      category: '飲料及點心',
      name: '可口可樂',
      enname:'coca-cola',
      calorie: 199,
      price: 38,
      image: '/images/beverages-and-snacks/coca-cola.jpg',
    },
    {
      category: '飲料及點心',
      name: '可口可樂zero',
      enname:'coca-cola-zero',
      calorie: 0,
      price: 38,
      image: '/images/beverages-and-snacks/coca-cola-zero.jpg',
    },
    {
      category: '飲料及點心',
      name: '玉米湯',
      enname:'corn-soup',
      calorie: 93,
      price: 40,
      image: '/images/beverages-and-snacks/corn-soup-small.jpg',
    },
    {
      category: '飲料及點心',
      name: '蜂蜜紅茶',
      enname:'iced honey blacktea',
      calorie: 134,
      price: 55,
      image: '/images/beverages-and-snacks/honey-black-tea-iced.jpg',
    },
    {
      category: '飲料及點心',
      name: '蜂蜜那堤',
      enname:'honey-latte',
      calorie: 249,
      price: 90,
      image: '/images/beverages-and-snacks/honey-latte.jpg',
    },
    {
      category: '飲料及點心',
      name: '冰蜂蜜那堤',
      enname:'iced honey-latte',
      calorie: 210,
      price: 90,
      image: '/images/beverages-and-snacks/honey-latte-iced.jpg',
    },
    {
      category: '飲料及點心',
      name: '冰蜂蜜奶茶',
      enname:'iced honey-milktea',
      calorie: 215,
      price: 65,
      image: '/images/beverages-and-snacks/honey-milk-tea-iced.jpg',
    },
    {
      category: '飲料及點心',
      name: '熱紅茶',
      enname:'hot-black-tea',
      calorie: 0,
      price: 38,
      image: '/images/beverages-and-snacks/hot-tea.jpg',
    },
    {
      category: '飲料及點心',
      name: '冰檸檬紅茶',
      enname:'iced-blacktea-lemon-flavor',
      calorie: 117,
      price: 38,
      image: '/images/beverages-and-snacks/iced-black-tea-lemonflavored.jpg',
    },
    {
      category: '飲料及點心',
      name: '冰無糖紅茶',
      enname:'iced-black-tea-sugar-free',
      calorie: 3,
      price: 38,
      image: '/images/beverages-and-snacks/iced-black-tea-sugarfree.jpg',
    },
    {
      category: '飲料及點心',
      name: '冰無糖綠茶',
      enname:'iced-green-tea-sugar-free',
      calorie: 0,
      price: 38,
      image: '/images/beverages-and-snacks/iced-green-tea-sugarfree.jpg',
    },
    {
      category: '飲料及點心',
      name: '經典那堤',
      enname:'latte',
      calorie: 117,
      price: 75,
      image: '/images/beverages-and-snacks/latte-hot.jpg',
    },
    {
      category: '飲料及點心',
      name: '蘋果派',
      enname:'applepie',
      calorie: 229,
      price: 35,
      image: '/images/beverages-and-snacks/applepie.jpg',
    },
    {
      category: '飲料及點心',
      name: '漢堡',
      enname:'Burger',
      calorie: 267,
      price: 38,
      image: '/images/beverages-and-snacks/Burger.jpg',
    },
    {
      category: '飲料及點心',
      name: '吉事漢堡',
      enname:'Cheeseburger',
      calorie: 178,
      price: 38,
      image: '/images/beverages-and-snacks/cheese-burger.jpg',
    },
    {
      category: '飲料及點心',
      name: '麥克鷄塊(4塊)',
      enname:'chicken-mcnuggets-4-pieces',
      calorie: 180,
      price: 49,
      image: '/images/beverages-and-snacks/Chicken-McNuggets-4pcs.jpg',
    },
    {
      category: '飲料及點心',
      name: '玉米杯',
      enname:'corn-cup',
      calorie: 86,
      price: 38,
      image: '/images/beverages-and-snacks/Corn-cup.jpg',
    },
    {
      category: '飲料及點心',
      name: '麥克鷄塊(6塊)',
      enname:'chicken-mcnuggets-6-pieces',
      calorie: 270,
      price: 64,
      image: '/images/beverages-and-snacks/EVM-06-NGT6.jpg',
    },
    {
      category: '飲料及點心',
      name: '麥克鷄塊(10塊)',
      enname:'chicken-mcnuggets-10-pieces',
      calorie: 449,
      price: 104,
      image: '/images/beverages-and-snacks/EVM-06-NGT10.jpg',
    },
    
    {
      category: '飲料及點心',
      name: '水果袋',
      enname:'sliced-apple',
      calorie: 36,
      price: 39,
      image: '/images/beverages-and-snacks/Fruit-Bag.jpg',
    },
    {
      category: '飲料及點心',
      name: '冰心雪糕',
      enname:'hand-dip-cone',
      calorie: 241,
      price: 25,
      image: '/images/beverages-and-snacks/hand-dig-cone.jpg',
    },
    {
      category: '飲料及點心',
      name: '薯餅',
      enname:'hash-browns',
      calorie: 152,
      price: 30,
      image: '/images/beverages-and-snacks/hash-browns.jpg',
    },
    {
      category: '飲料及點心',
      name: '大蛋捲冰淇淋',
      enname:'ice-cream-cone-large',
      calorie: 202,
      price: 30,
      image: '/images/beverages-and-snacks/large-ice-cream-cone.jpg',
    },
    {
      category: '飲料及點心',
      name: '蛋捲冰淇淋',
      enname:'ice-cream-cone',
      calorie: 145,
      price: 18,
      image: '/images/beverages-and-snacks/ice-cream-cone.jpg',
    },
    {
      category: '飲料及點心',
      name: '冰炫風(OREO)',
      enname:'mcflurry',
      calorie: 352,
      price: 55,
      image: '/images/beverages-and-snacks/mcflurry-oreo.jpg',
    },
    {
      category: '飲料及點心',
      name: '四季沙拉(大)',
      enname:'salad-large',
      calorie: 37,
      price: 45,
      image: '/images/beverages-and-snacks/salad-big.jpg',
    },
    {
      category: '飲料及點心',
      name: '勁辣香鷄翅(2塊)',
      enname:'spicy-chicken-wing-2-pieces',
      calorie: 292,
      price: 49,
      image: '/images/beverages-and-snacks/spicy-chicken-wings-2pcs.jpg',
    },
    {
      category: '飲料及點心',
      name: '勁辣香鷄翅(6塊)',
      enname:'spicy-chicken-wing-6-pieces',
      calorie: 875,
      price: 130,
      image: '/images/beverages-and-snacks/spicy-chicken-wings-6pcs.jpg',
    },
    {
      category: '飲料及點心',
      name: '酥嫩鷄翅(2塊)',
      enname:'tender-chicken-wing-2-pieces',
      calorie: 183,
      price: 49,
      image: '/images/beverages-and-snacks/tender-chicken-wings-2pcs.jpg',
    },
    {
      category: '飲料及點心',
      name: '酥嫩鷄翅(6塊)',
      enname:'tender-chicken-wing-6-pieces',
      calorie: 549,
      price: 130,
      image: '/images/beverages-and-snacks/tender-chicken-wings-6pcs.jpg',
    },
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////配餐
    {
      category: '配餐',
      name: '麥脆鷄翅(原味)',
      enname:'chicken-mccrispy-wing',
      calorie: 373,
      price: 68,
      image: '/images/side_meal/wings.jpg',
    },
    {
      category: '配餐',
      name: '麥脆鷄翅(辣味)',
      enname:'spicy-chicken-mccrispy-wing',
      calorie: 306,
      price: 68,
      image: '/images/side_meal/wingsSpicy.jpg',
    },
    {
      category: '配餐',
      name: '麥脆鷄腿(原味)',
      enname:'chicken-mccrispy',
      calorie: 373,
      price: 58,
      image: '/images/side_meal/chest.jpg',
    },
    {
      category: '配餐',
      name: '麥脆鷄腿(辣味)',
      enname:'spicy-chicken-mccrispy',
      calorie: 383,
      price: 58,
      image: '/images/side_meal/chestSpicy.jpg',
    },
    {
      category: '配餐',
      name: '勁辣香鷄翅(2塊)',
      enname:'spicy-chicken-wing-2-pieces',
      calorie: 292,
      price: 58,
      image: '/images/beverages-and-snacks/spicy-chicken-wings-2pcs.jpg',
    },
    {
      category: '配餐',
      name: '酥嫩鷄翅(2塊)',
      enname:'tender-chicken-wing-2-pieces',
      calorie: 183,
      price: 58,
      image: '/images/beverages-and-snacks/tender-chicken-wings-2pcs.jpg',
    },
    {
      category: '配餐',
      name: '麥克鷄塊(4塊)+中薯',
      enname:'chicken-mcnuggets-4-pieces+french-fries-medium',
      calorie: 556,
      price: 95,
      image: '/images/side_meal/friesMCG.jpg',
    },
    {
      category: '配餐',
      name: '麥脆鷄腿(原味)+中薯',
      enname:'chicken-mccrispy+french-fries-medium',
      calorie: 749,
      price: 110,
      image: '/images/side_meal/friesandcleg.jpg',
    },
    {
      category: '配餐',
      name: '麥脆鷄腿(辣味)+中薯',
      enname:'spicy-chicken-mccrispy+french-fries-medium',
      calorie: 759,
      price: 110,
      image: '/images/side_meal/friesandcleg.jpg',
    },
    {
      category: '配餐',
      name: '中薯',
      enname:'french-fries-medium',
      calorie: 376,
      price: 55,
      image: '/images/side_meal/fries-mid.jpg',
    },
    {
      category: '配餐',
      name: '大薯',
      enname:'french-fries-large',
      calorie: 529,
      price: 110,
      image: '/images/side_meal/fries-big.jpg',
    },
    {
      category: '配餐',
      name: '清爽沙拉',
      enname:'salad',
      calorie: 37,
      price: 55,
      image: '/images/side_meal/salad-big.jpg',
    },

    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////配餐飲料
    {
      category: '配餐飲料',
      name: '經典美式咖啡',
      enname:'americano',
      calorie: 14,
      price: 0,
      image: '/images/beverages-and-snacks/americano-hot.jpg',
    },
    {
      category: '配餐飲料',
      name: '冰經典美式咖啡',
      enname:'iced-americano',
      calorie: 19,
      price: 0,
      image: '/images/beverages-and-snacks/americano-iced.jpg',
    },
    {
      category: '配餐飲料',
      name: '阿薩姆鮮奶茶',
      enname:'assam-milktea',
      calorie: 183,
      price: +20,
      image: '/images/beverages-and-snacks/assam-milk-tea-hot.jpg',
    },
    {
      category: '配餐飲料',
      name: '冰阿薩姆鮮奶茶',
      enname:'iced-assam-milktea',
      calorie: 183,
      price: +20,
      image: '/images/beverages-and-snacks/assam-milk-tea-iced.jpg',
    },
    {
      category: '配餐飲料',
      name: '中杯可口可樂',
      enname:'coke-medium',
      calorie: 199,
      price: 0,
      image: '/images/beverages-and-snacks/coca-cola.jpg',
    },
    {
      category: '配餐飲料',
      name: '大杯可口可樂',
      enname:'coke-large',
      calorie: 298,
      price: +10,
      image: '/images/beverages-and-snacks/coca-cola.jpg',
    },
    {
      category: '配餐飲料',
      name: '中杯可口可樂zero',
      enname:'coke-zero-medium',
      calorie: 0,
      price: 0,
      image: '/images/beverages-and-snacks/coca-cola-zero.jpg',
    },
    {
      category: '配餐飲料',
      name: '大杯可口可樂zero',
      enname:'coke-zero-large',
      calorie: 0,
      price: +10,
      image: '/images/beverages-and-snacks/coca-cola-zero.jpg',
    },
    {
      category: '配餐飲料',
      name: '玉米湯',
      enname:'corn-soup-small',
      calorie: 93,
      price: 0,
      image: '/images/beverages-and-snacks/corn-soup-small.jpg',
    },
    {
      category: '配餐飲料',
      name: '大杯玉米湯',
      enname:'corn-soup-large',
      calorie: 140,
      price: +10,
      image: '/images/beverages-and-snacks/corn-soup-small.jpg',
    },
    {
      category: '配餐飲料',
      name: '蜂蜜紅茶',
      enname:'honey-black-tea-iced',
      calorie: 134,
      price: 0,
      image: '/images/beverages-and-snacks/honey-black-tea-iced.jpg',
    },
    {
      category: '配餐飲料',
      name: '蜂蜜那堤',
      enname:'honey-latte',
      calorie: 249,
      price: +20,
      image: '/images/beverages-and-snacks/honey-latte.jpg',
    },
    {
      category: '配餐飲料',
      name: '冰蜂蜜那堤',
      enname:'honey-latte-iced',
      calorie: 210,
      price: +20,
      image: '/images/beverages-and-snacks/honey-latte-iced.jpg',
    },
    {
      category: '配餐飲料',
      name: '冰蜂蜜奶茶',
      enname:'/honey-milktea-iced',
      calorie: 215,
      price: +20,
      image: '/images/beverages-and-snacks/honey-milk-tea-iced.jpg',
    },
    {
      category: '配餐飲料',
      name: '熱紅茶',
      enname:'hot-black-tea',
      calorie: 0,
      price: 0,
      image: '/images/beverages-and-snacks/hot-tea.jpg',
    },
    {
      category: '配餐飲料',
      name: '中杯冰檸檬紅茶',
      enname:'iced-black-tea-lemon-flavor-medium',
      calorie: 157,
      price: 0,
      image: '/images/beverages-and-snacks/iced-black-tea-lemonflavored.jpg',
    },
    {
      category: '配餐飲料',
      name: '大杯冰檸檬紅茶',
      enname:'iced-black-tea-lemon-flavor-large',
      calorie: 234,
      price: +10,
      image: '/images/beverages-and-snacks/iced-black-tea-lemonflavored.jpg',
    },
    {
      category: '配餐飲料',
      name: '中杯冰無糖紅茶',
      enname:'iced-black-tea-sugar-free-medium',
      calorie: 3,
      price: 0,
      image: '/images/beverages-and-snacks/iced-black-tea-sugarfree.jpg',
    },
    {
      category: '配餐飲料',
      name: '大杯冰無糖紅茶',
      enname:'iced-black-tea-sugar-free-large',
      calorie: 3,
      price: +10,
      image: '/images/beverages-and-snacks/iced-black-tea-sugarfree.jpg',
    },
    {
      category: '配餐飲料',
      name: '中杯冰無糖綠茶',
      enname:'iced-green-tea-sugar-free-medium',
      calorie: 0,
      price: 0,
      image: '/images/beverages-and-snacks/iced-green-tea-sugarfree.jpg',
    },
    {
      category: '配餐飲料',
      name: '大杯冰無糖綠茶',
      enname:'iced-green-tea-sugar-free-large',
      calorie: 0,
      price: +10,
      image: '/images/beverages-and-snacks/iced-green-tea-sugarfree.jpg',
    },
    {
      category: '配餐飲料',
      name: '經典那堤',
      enname:'latte',
      calorie: 117,
      price: +10,
      image: '/images/beverages-and-snacks/latte-hot.jpg',
    },
    {
      category: '配餐飲料',
      name: '冰經典那堤',
      enname:'iced-latte',
      calorie: 111,
      price: +10,
      image: '/images/beverages-and-snacks/latte-iced.jpg',
    },
    {
      category: '配餐飲料',
      name: '鮮乳',
      enname:'Milk',
      calorie: 160,
      price: 0,
      image: '/images/beverages-and-snacks/Milk.jpg',
    },
    {
      category: '配餐飲料',
      name: '熱奶茶',
      enname:'hot-milktea',
      calorie: 36,
      price: +10,
      image: '/images/beverages-and-snacks/milk-tea-hot.jpg',
    },
    {
      category: '配餐飲料',
      name: '冰奶茶',
      enname:'iced-milktea',
      calorie: 128,
      price: +10,
      image: '/images/beverages-and-snacks/milk-tea-iced.jpg',
    },
    {
      category: '配餐飲料',
      name: '柳橙汁',
      enname:'orange-juice',
      calorie: 154,
      price: 0,
      image: '/images/beverages-and-snacks/Orange-Juice.jpg',
    },
    {
      category: '配餐飲料',
      name: '中杯雪碧',
      enname:'sprite-medium',
      calorie: 218,
      price: 0,
      image: '/images/beverages-and-snacks/sprite.jpg',
    },
    {
      category: '配餐飲料',
      name: '大杯雪碧',
      enname:'sprite-large',
      calorie: 327,
      price: +10,
      image: '/images/beverages-and-snacks/sprite.jpg',
    },
    
    //////////////////////////////////////////////////////////////////////////////////////////////////////銅板輕鬆點
    {
      category: '銅板輕鬆點',
      name: '吉事漢堡+可樂(小)',
      enname:'cheese-burger-and-coke',
      calorie: 327,
      price: 50,
      image: '/images/50-dollars-meal/BA_Combo-2-1.jpg',
    },
    {
      category: '銅板輕鬆點',
      name: '法式芥末香鷄堡+熱紅茶(小)',
      enname:'honey-mustard-chicken-burger-and-hot-blacktea',
      calorie: 366,
      price: 50,
      image: '/images/50-dollars-meal/BA_Combo-1.jpg',
    },
    {
      category: '銅板輕鬆點',
      name: '四塊麥克鷄塊+玉米湯(小)',
      enname:'chicken-mcnuggets-4-pieces-and-corn-soup',
      calorie: 273,
      price: 50,
      image: '/images/50-dollars-meal/BA_Combo-3.jpg',
    },
    {
      category: '銅板輕鬆點',
      name: '酥嫩鷄翅(一份兩塊)+可樂(小)',
      enname:'tender-chicken-wing-and-coke',
      calorie: 332,
      price: 50,
      image: '/images/50-dollars-meal/BA_Combo-4.jpg',
    },
    {
      category: '銅板輕鬆點',
      name: '勁辣香鷄翅(一份兩塊)+冰紅茶(檸檬風味)(小)',
      enname:'spicy-chicken-wing-and-fuze-tea',
      calorie: 409,
      price: 50,
      image: '/images/50-dollars-meal/BA_Combo-5.jpg',
    },
    {
      category: '銅板輕鬆點',
      name: '大蛋捲冰淇淋+雪碧(小)',
      enname:'ice-cream-cone-large-and-sprite',
      calorie: 365 ,
      price: 50,
      image: '/images/50-dollars-meal/BA_Combo-6-1.jpg',
    },
    {
      category: '銅板輕鬆點',
      name: '蘋果派+熱紅茶(小)',
      enname:'apple-pie-and-hot-black-tea',
      calorie: 235,
      price: 50,
      image: '/images/50-dollars-meal/BA_Combo-7.jpg',
    },
    {
      category: '銅板輕鬆點',
      name: '薯條(小包)+雪碧(小)',
      enname:'french-fries-and-sprite',
      calorie: 428,
      price: 50,
      image: '/images/50-dollars-meal/BA_Combo-8.jpg',
    },
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////happy meal
    {
      category: 'Happy Meal',
      name: '四塊麥克鷄塊Happy Meal',
      enname:'chicken-mcnuggets-4-pieces-happy-meal',
      calorie: 420,
      price: 89,
      image: '/images/happy-meal/Combo-Chicken-McNuggets.jpg',
    },
    {
      category: 'Happy Meal',
      name: '漢堡Happy Meal',
      enname:'burger-happy-meal',
      calorie: 535,
      price: 89,
      image: '/images/happy-meal/Combo-Burger.jpg',
    },
    {
      category: 'Happy Meal',
      name: '陽光鱈魚堡Happy Meal',
      enname:'mcfish-happy-meal',
      calorie: 453,
      price: 89,
      image: '/images/happy-meal/Combo-McFish.jpg',
    },
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////加價購
    {
      category: '加價購',
      name: '優惠$32 蘋果派(原價$35)',
      enname:'discount$32 applepie(origin$35)',
      calorie: 229,
      price: 32,
      image: '/images/extra/applepie.jpg',
    },
    {
      category: '加價購',
      name: '優惠$55 六塊麥克鷄塊(原價$69)',
      enname:'discount$55 chicken-mcnuggets-6-pieces(origin$69)',
      calorie: 270,
      price: 55,
      image: '/images/extra/EVM-06-NGT6.jpg',
    },
    {
      category: '加價購',
      name: '優惠$45 四塊麥克鷄塊(原價$49)',
      enname:'discount$45 chicken-mcnuggets-4-pieces(origin$49)',
      calorie: 180,
      price: 45,
      image: '/images/extra/Chicken-McNuggets-4pcs.jpg',
    },
    {
      category: '加價購',
      name: '優惠$40 勁辣香鷄翅(原價$45)',
      enname:'discount$40 spicy-chicken-wing(origin$45)',
      calorie: 146,
      price: 40,
      image: '/images/extra/spicy-chicken-wings-2pcs.jpg',
    },
    {
      category: '加價購',
      name: '優惠$40 酥嫩鷄翅(原價$45)',
      enname:'discount$40 tender-chicken-wing(origin$45)',
      calorie: 146,
      price: 40,
      image: '/images/extra/tender-chicken-wings-2pcs.jpg',
    },
  ],
};

module.exports = data;
